version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: notes-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: notes-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:5050"

volumes:
  postgres-data: