name: GitOps - Update K8s Manifests

on:
  workflow_run:
    workflows: ["CI - Build, Test, Scan, Push"]
    types:
      - completed

env:
  GITOPS_REPO: turbo-badex/notes-app
  GITOPS_BRANCH: main

jobs:
  update-k8s-manifest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download IMAGE_TAG artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI - Build, Test, Scan, Push
          name: image-tag
          run_id: ${{ github.event.workflow_run.id }}

      - name: Read IMAGE_TAG
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_PAT }}
          ref: ${{ env.GITOPS_BRANCH }}

      - name: Update deployment manifest with new image
        run: |
          sed -i "s|image: .*/flask-notes:.*|image: ${{ secrets.DOCKER_USERNAME }}/flask-notes:${{ env.IMAGE_TAG }}|g" flask-app/deployment.yaml

      - name: Commit and push update
        run: |
          git config user.name "turbo-badex"
          git config user.email "taiwo@badex.tv"
          git add flask-app/deployment.yaml
          git commit -m "GitOps: Update image to ${{ env.IMAGE_TAG }}"
          git push origin ${{ env.GITOPS_BRANCH }}