name: CI - Build, Test, Scan, Push, Update GitOps

on:
  push:
    branches: [main]
permissions:
  contents: read
  security-events: write

env:
  GITOPS_REPO: turbo-badex/notes-app
  GITOPS_BRANCH: main

jobs:
  build-test-scan-push:
    name: Build, Test, Scan, Push, Update GitOps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Set FLASK_ENV
        run: echo "FLASK_ENV=testing" >> $GITHUB_ENV

      - name: Confirm FLASK_ENV
        run: echo "FLASK_ENV is $FLASK_ENV"

      - name: Run Unit Tests and Coverage
        run: |
          PYTHONPATH=. pytest --cov=app --cov-report=term --cov-report=xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image locally
        run: |
          IMAGE_TAG=v$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-notes:$IMAGE_TAG .

      - name: Run Trivy scan with SARIF output
        continue-on-error: true  # ✅ Ensures pipeline doesn't fail on findings
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/flask-notes:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Upload Trivy SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy SARIF report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif-report
          path: trivy-results.sarif

      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-notes:${{ env.IMAGE_TAG }}

      - name: Clone GitOps repo
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "taiwo@badex.tv"
          git config --global user.name "turbo-badex"
          git clone https://${{ secrets.GITOPS_PAT }}@github.com/${{ env.GITOPS_REPO }} gitops
          cd gitops
          sed -i "s|image: .*/flask-notes:.*|image: ${{ secrets.DOCKER_USERNAME }}/flask-notes:${{ env.IMAGE_TAG }}|g" flask-app/deployment.yaml
          git add flask-app/deployment.yaml
          git commit -m "CI: Update image to ${{ env.IMAGE_TAG }}"
          git push origin ${{ env.GITOPS_BRANCH }}